# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelAPI
pod 'Alamofire', '~> 5.4.3'
pod 'Cartography', '~> 4.0.0'
pod 'Kingfisher', '~> 6.3.0'


  target 'MarvelAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAPIUITests' do
    # Pods for testing
  end

end
